import React, { useState } from 'react';
import { UserRole, RolePermissions } from '../../types';
import { INITIAL_ROLE_PERMISSIONS } from '../../data/governanceData';
import {
  ShieldCheck,
  Check,
  X,
  AlertTriangle,
  Info,
  Users,
  Lock,
  Save,
  CheckCircle2,
  Sliders,
  ChevronRight,
} from 'lucide-react';

export const ScreenRolePermission: React.FC = () => {
  const [rolePermissionsList, setRolePermissionsList] = useState<RolePermissions[]>(INITIAL_ROLE_PERMISSIONS);
  const [selectedRoleName, setSelectedRoleName] = useState<UserRole>('Executive / Management');
  const [saveSuccessNotice, setSaveSuccessNotice] = useState(false);

  const activeRoleConfig =
    rolePermissionsList.find((r) => r.role === selectedRoleName) || rolePermissionsList[0];

  const handleTogglePermission = (
    groupKey: keyof RolePermissions['permissions'],
    permKey: string
  ) => {
    setRolePermissionsList((prev) =>
      prev.map((r) => {
        if (r.role !== selectedRoleName) return r;
        const currentVal = (r.permissions[groupKey] as any)[permKey];
        return {
          ...r,
          permissions: {
            ...r.permissions,
            [groupKey]: {
              ...r.permissions[groupKey],
              [permKey]: !currentVal,
            },
          },
        };
      })
    );
  };

  const handleSave = () => {
    setSaveSuccessNotice(true);
    setTimeout(() => {
      setSaveSuccessNotice(false);
    }, 3500);
  };

  const PERMISSION_GROUPS_DEF = [
    {
      groupKey: 'overview' as const,
      label: 'OVERVIEW',
      description: 'High-level executive KPIs, decision posture, and portfolio synthesis.',
      items: [
        {
          key: 'viewExecutiveOverview',
          label: 'View Executive Overview',
          desc: 'Access the executive portfolio scorecard, priority role counts, and high-impact macro insights.',
        },
      ],
    },
    {
      groupKey: 'where' as const,
      label: 'WHERE',
      description: 'Geospatial distribution, interactive basemap, and territorial boundaries.',
      items: [
        {
          key: 'viewStrategicActionMap',
          label: 'View Strategic Action Map',
          desc: 'Interactive Semarang map with hexagonal bins and polygon administrative layers.',
        },
        {
          key: 'viewAllRegions',
          label: 'View All Regions',
          desc: 'Unrestricted capability to browse all provincial jurisdictions without territory lockout.',
        },
      ],
    },
    {
      groupKey: 'protect' as const,
      label: 'PROTECT',
      description: 'Customer base retention, VIP churn risk mitigation, and competitive defense.',
      items: [
        {
          key: 'viewRetention',
          label: 'View Retention',
          desc: 'High-risk customer cluster inspection, ARPU protection, and proactive renewal targeting.',
        },
        {
          key: 'viewMarketShareDefense',
          label: 'View Market Share Defense',
          desc: 'Competitor footprint counter-moves, price-to-value speed matching, and churn vulnerability radar.',
        },
      ],
    },
    {
      groupKey: 'grow' as const,
      label: 'GROW',
      description: 'Commercial acquisition and physical capex infrastructure expansion.',
      items: [
        {
          key: 'viewAcquisition',
          label: 'View Acquisition',
          desc: 'Addressable greenfield market demand, competitor displacement, and high-yield leads.',
        },
        {
          key: 'viewNetworkExpansion',
          label: 'View Network Expansion',
          desc: 'Multi-gate feasibility screening, capex preservation protocols, and infrastructure readiness.',
        },
      ],
    },
    {
      groupKey: 'understand' as const,
      label: 'UNDERSTAND',
      description: 'Candidate micro-intelligence and transparent mathematical evidence.',
      items: [
        {
          key: 'viewCandidateDetail',
          label: 'View Candidate Detail',
          desc: 'Comprehensive dossier on individual kecamatan, micro-cells, demographics, and metrics.',
        },
        {
          key: 'viewExplainability',
          label: 'View Explainability',
          desc: 'Full transparent evidence: Champion model metrics, AHP matrix weights, and SHAP attribution.',
        },
      ],
    },
    {
      groupKey: 'decide' as const,
      label: 'DECIDE',
      description: 'Operational action execution, budget sign-off, and cross-functional directives.',
      items: [
        {
          key: 'viewRecommendation',
          label: 'View Recommendation',
          desc: 'Review strategic blueprint recommendations generated by the multi-objective engine.',
        },
        {
          key: 'approveRecommendation',
          label: 'Approve Recommendation',
          desc: 'Formal executive authorization to transition recommendation from REVIEWED to APPROVED state.',
        },
      ],
    },
    {
      groupKey: 'govern' as const,
      label: 'GOVERN',
      description: 'Platform access administration, user provisioning, security, and auditing.',
      items: [
        {
          key: 'manageUsers',
          label: 'Manage Users',
          desc: 'Create, update, deactivate corporate user accounts, and assign regional jurisdictions.',
        },
        {
          key: 'manageRoles',
          label: 'Manage Roles',
          desc: 'Configure role-based access matrix permissions across the platform.',
        },
        {
          key: 'viewAuditLogs',
          label: 'View Audit Logs',
          desc: 'Inspect tamper-proof telemetry logs for logins, data access, and recommendation sign-offs.',
        },
        {
          key: 'manageApplicationSettings',
          label: 'Manage Application Settings',
          desc: 'Configure global system parameters, SSO authentication, and decision framework versioning.',
        },
      ],
    },
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 pb-3 border-b border-slate-200">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-[11px] font-bold text-slate-500 uppercase tracking-widest font-mono">
              SCREEN • GOVERNANCE
            </span>
            <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-purple-50 text-purple-700 border border-purple-200">
              RBAC Policy Engine
            </span>
          </div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight mt-1">
            Role &amp; Permission
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Configure what each SERVEON role can see and do across geospatial, commercial, and administrative modules.
          </p>
        </div>

        {/* Primary CTA */}
        <div className="flex items-center gap-3">
          {saveSuccessNotice && (
            <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-50 text-emerald-800 border border-emerald-200 text-xs font-semibold animate-in fade-in">
              <CheckCircle2 className="w-4 h-4 text-emerald-600" />
              <span>Permissions Updated Successfully</span>
            </div>
          )}

          <button
            onClick={handleSave}
            className="px-4 py-2 rounded-lg bg-blue-900 hover:bg-blue-800 text-white font-bold text-xs tracking-wider uppercase transition-all shadow-xs flex items-center gap-1.5 active:scale-[0.99] cursor-pointer"
          >
            <Save className="w-4 h-4" />
            <span>Save Permissions</span>
          </button>
        </div>
      </div>

      {/* Notice Banner */}
      <div className="p-3.5 rounded-xl bg-amber-50/80 border border-amber-200 flex items-center justify-between text-xs">
        <div className="flex items-center gap-2.5 text-amber-900">
          <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0" />
          <span>
            <strong className="font-semibold">Security Requirement:</strong> Permission changes require administrator authorization and are permanently recorded in the immutable audit trail.
          </span>
        </div>
        <span className="text-[11px] font-mono text-amber-800 font-medium hidden md:inline">
          Policy Ver: 2026.3-RBAC
        </span>
      </div>

      {/* Main Two-Panel Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* LEFT PANEL: ROLES LIST */}
        <div className="lg:col-span-4 bg-white rounded-xl border border-slate-200 shadow-2xs p-3 space-y-1.5">
          <div className="px-3 py-2 text-[11px] font-bold text-slate-500 uppercase tracking-wider border-b border-slate-100 flex items-center justify-between">
            <span>PLATFORM ROLES (8)</span>
            <span className="text-[10px] text-slate-400 font-mono">Assigned Users</span>
          </div>

          <div className="space-y-1">
            {rolePermissionsList.map((r) => {
              const isSelected = r.role === selectedRoleName;
              return (
                <button
                  key={r.role}
                  onClick={() => setSelectedRoleName(r.role)}
                  className={`w-full text-left p-3 rounded-lg transition-all flex items-center justify-between ${
                    isSelected
                      ? 'bg-blue-900 text-white shadow-xs'
                      : 'hover:bg-slate-50 text-slate-800'
                  }`}
                >
                  <div className="pr-2 truncate">
                    <div className="font-bold text-xs truncate flex items-center gap-1.5">
                      <span>{r.role}</span>
                      {r.role === 'Executive / Management' && (
                        <span
                          className={`text-[9px] px-1.5 py-0.2 rounded font-mono font-medium ${
                            isSelected
                              ? 'bg-blue-800 text-blue-200'
                              : 'bg-indigo-50 text-indigo-700 border border-indigo-200'
                          }`}
                        >
                          Sign-Off
                        </span>
                      )}
                    </div>
                    <div
                      className={`text-[11px] mt-0.5 line-clamp-1 ${
                        isSelected ? 'text-blue-200' : 'text-slate-500'
                      }`}
                    >
                      {r.description}
                    </div>
                  </div>

                  <div className="flex items-center gap-2 shrink-0">
                    <span
                      className={`text-[10.5px] font-mono px-2 py-0.5 rounded-full font-bold ${
                        isSelected
                          ? 'bg-blue-800 text-white'
                          : 'bg-slate-100 text-slate-600'
                      }`}
                    >
                      {r.userCount}
                    </span>
                    <ChevronRight
                      className={`w-4 h-4 ${isSelected ? 'text-white' : 'text-slate-400'}`}
                    />
                  </div>
                </button>
              );
            })}
          </div>
        </div>

        {/* RIGHT PANEL: PERMISSION MATRIX */}
        <div className="lg:col-span-8 bg-white rounded-xl border border-slate-200 shadow-2xs p-5 space-y-6">
          {/* Active Role Header */}
          <div className="pb-4 border-b border-slate-200 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-lg font-bold text-slate-900">
                  {activeRoleConfig.role}
                </h2>
                <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-blue-50 text-blue-700 border border-blue-200 font-mono">
                  {activeRoleConfig.userCount} Active Users
                </span>
              </div>
              <p className="text-xs text-slate-500 mt-1">
                {activeRoleConfig.description}
              </p>
            </div>

            <div className="text-[11px] text-slate-500 bg-slate-50 px-3 py-1.5 rounded-lg border border-slate-200">
              Status: <span className="text-emerald-700 font-bold">Policy Active</span>
            </div>
          </div>

          {/* Groups Matrix */}
          <div className="space-y-6">
            {PERMISSION_GROUPS_DEF.map((group) => (
              <div key={group.groupKey} className="space-y-3">
                <div className="flex items-center justify-between pb-1.5 border-b border-slate-100">
                  <div>
                    <h3 className="text-xs font-bold text-slate-900 tracking-wider font-mono uppercase">
                      {group.label}
                    </h3>
                    <p className="text-[11px] text-slate-400">{group.description}</p>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
                  {group.items.map((item) => {
                    const isAllowed = (activeRoleConfig.permissions[group.groupKey] as any)[
                      item.key
                    ];

                    return (
                      <div
                        key={item.key}
                        onClick={() => handleTogglePermission(group.groupKey, item.key)}
                        className={`p-3 rounded-lg border transition-all cursor-pointer select-none flex items-start justify-between gap-3 ${
                          isAllowed
                            ? 'bg-blue-50/40 border-blue-200 text-slate-900'
                            : 'bg-slate-50/50 border-slate-200 text-slate-500 opacity-75'
                        }`}
                      >
                        <div>
                          <div className="font-semibold text-xs flex items-center gap-1.5">
                            <span className={isAllowed ? 'text-slate-900' : 'text-slate-600'}>
                              {item.label}
                            </span>
                          </div>
                          <p className="text-[10.5px] text-slate-500 mt-0.5 leading-snug">
                            {item.desc}
                          </p>
                        </div>

                        {/* Switch UI */}
                        <div
                          className={`w-9 h-5 rounded-full transition-colors relative shrink-0 mt-0.5 ${
                            isAllowed ? 'bg-blue-600' : 'bg-slate-300'
                          }`}
                        >
                          <div
                            className={`w-4 h-4 rounded-full bg-white shadow-xs absolute top-0.5 transition-transform ${
                              isAllowed ? 'left-[18px]' : 'left-0.5'
                            }`}
                          />
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>

          {/* Matrix Footer Action */}
          <div className="pt-4 border-t border-slate-200 flex items-center justify-between">
            <span className="text-[11px] text-slate-400">
              Click any toggle to stage permission adjustment.
            </span>
            <button
              onClick={handleSave}
              className="px-4 py-2 rounded-lg bg-blue-900 hover:bg-blue-800 text-white font-bold text-xs tracking-wider uppercase transition-colors shadow-xs"
            >
              Save Permissions
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
